// @ts-ignore
/* eslint-disable */
// Code generated by protoc-gen-ts-umi. DO NOT EDIT.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.

declare namespace RealotzApiV1 {
	/** ListOption */
	type ListOption = {
		limit?:number
		continue?:string
		labelSelector?:string
		fieldSelector?:string
		namespace?:string
	}
	/** GatewayList */
	type GatewayList = {
		list?:Array<RealotzApiV1.Gateway>
	}
	/** Gateway */
	type Gateway = {
		apiVersion?:string
		kind?:string
	}
	/** GetKind */
	type GetKind = {
		name?:string
		namespace?:string
		version?:string
	}
	/** DeleteKind */
	type DeleteKind = {
		name?:string
		namespace?:string
	}
	/** Request */
	type Request = {
	}
	/** Response */
	type Response = {
	}
}

